services:
  elicelab_reservation_nginx:
    image: nginx:stable-alpine
    container_name: elicelab_reservation_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates
      - ./.cert/cert.pem:/etc/nginx/.cert/cert.pem
      - ./.cert/key.pem:/etc/nginx/.cert/key.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - elicelab_reservation_nestjs_01
      - elicelab_reservation_nestjs_02
      - elicelab_reservation_minio
    networks:
      - elice_network

  elicelab_reservation_nestjs_01:
    container_name: elicelab_reservation_nestjs_01
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: development
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    command: npm run start:dev
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - elicelab_reservation_postgres
      - elicelab_reservation_redis
      - elicelab_reservation_minio
    networks:
      - elice_network

  elicelab_reservation_nestjs_02:
    container_name: elicelab_reservation_nestjs_02
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: development
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    command: npm run start:dev
    ports:
      - "8001:${SERVER_PORT}"
    depends_on:
      - elicelab_reservation_postgres
      - elicelab_reservation_redis
      - elicelab_reservation_minio
    networks:
      - elice_network
  
  
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - "8000:8000"
  #    env_file:
  #      - .env
  #    depends_on:
  #      - elicelab_reservation_postgres
  #      - elicelab_reservation_redis
  #      - elicelab_reservation_minio
  #    networks:
  #      - elice_network
  #    volumes:
  #      - .:/app
  elicelab_reservation_postgres:
    container_name: elicelab_reservation_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    networks:
      - elice_network
  elicelab_reservation_redis:
    container_name: elicelab_reservation_redis
    image: "redis:alpine"
    env_file:
      - ./backend/.env
    ports:
      - "6379:6379"
    networks:
      - elice_network
  #  minio:
  ##    image: docker.io/bitnami/minio:2022
  #    container_name: elicelab_reservation_minio
  #    image: minio/minio:latest
  #    command: server /data --console-address ":9001"
  #    env_file:
  #      - .env
  #    ports:
  #      - "9000:9000"
  #      - "9001:9001"
  #    volumes:
  #      - ./data:/data
  ##    networks:
  ##      - elice_network
  elicelab_reservation_minio:
    container_name: elicelab_reservation_minio
    image: docker.io/bitnami/minio:2022
    env_file:
      - ./backend/.env
    ports:
      - '9000:9000'
      - '9001:9001'
    platform: linux/amd64
    networks:
      - elice_network

networks:
  elice_network: # 기본 네트워크를 명시적으로 설정
    name: elicelab_reservation_project_elice_network
    driver: bridge